server:
  port: 8001 # 服务端口号

spring:
  application:
    name: service-edu # 服务名
  profiles:
    active: dev # 开发环境

  datasource: # 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/guli_parent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 111225

  jackson:  # 设置JSON时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos地址

  redis:              # redis设置
    host: 11111111111111
    port: 6379
    password: 111225
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0


#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/nfgj/edu/mapper/xml/*.xml


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis日志
#
#logging:
#  level:

# 开启熔断器
feign:
  hystrix:
    enabled: true





#    root: WARN # 设置日志级别